.386
.MODEL flat, stdcall
OPTION casemap:none	
INCLUDE		\masm32\include\windows.inc		
INCLUDE     \masm32\include\kernel32.inc
INCLUDE		\masm32\include\masm32.inc
INCLUDE		\masm32\include\masm32rt.inc
.DATA
	I DB (0), 0
	J DB (0), 0
	TAM DB (0) ;TAMAÑO DE MATRIZ I*J
	MATRIZ DB 100 DUP (0)
.DATA?
	
.CODE
PROGRAMA:
	; TANTO J COMO I DEBEN DE SER DE UN SOLO DIGITO
	print chr$("Ingrese N", 13, 10) ;FILAS = I = N
	INVOKE StdIn, ADDR I, 3
	print chr$("Ingrese M", 13, 10) ;COLUMNAS = J = M
	INVOKE StdIn, ADDR J, 3
	SUB I, 30H
	SUB J, 30H
	MOV AL, I
	MUL J
	MOV TAM, AL ;GUARDO EL TAMAÑO DE LA MATRIZ J*I
	CALL LLENAR
	CALL LIMPIAR
	CALL IMPRIMIR

	INVOKE ExitProcess,0

; ---------- PROCEDIMIENTOS ---------------
LIMPIAR PROC NEAR ;LIMPIA REGISTROS
	XOR EAX, EAX
	XOR EBX, EBX
	XOR ECX, ECX
	XOR EDX, EDX
RET
LIMPIAR ENDP

LLENAR PROC NEAR
	CALL LIMPIAR
	LEA ESI, MATRIZ
	MOV AL, 0H ;AL ES EL CONTADOR
	
	FOR_J:
		MOV [ESI], AL
		INC ESI
		INC AL
		CMP AL, TAM
		JZ END_FORJ
		JMP FOR_J
	END_FORJ:
RET
LLENAR ENDP

IMPRIMIR PROC NEAR
	;CADA J IMPRIMIR ENTER

	MOV TAM, 0H ;COMO TAM YA NO SE USA LA PUEDO USAR DE AUX
	LEA ESI, MATRIZ
	SUB J, 01H
	FOR_I:
		MOV AL, [ESI]
		print str$(AL)
		print chr$("	")

		INC ESI
		MOV AL, [ESI]

		MOV BL, TAM
		CMP BL, J
		JZ ENTER1
		INC TAM

		JMP CONTINUAR
		ENTER1:
			MOV I, AL ;COMO YA NO UTILIZO I ACA SE VUELVE UN AUX MAS
			print chr$(" ", 13,10)
			CALL LIMPIAR
			MOV AL, I
			MOV TAM, 0H
		CONTINUAR:
			CMP AL, 0
			JZ END_FORI
			JMP FOR_I
	END_FORI:

RET
IMPRIMIR ENDP

END PROGRAMA